# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 11:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_date',
        ),
        migrations.AddField(
            model_name='article',
            name='article_created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 18, 11, 38, 30, 820023, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='article',
            name='article_published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
